### ISSUE TITLE
Dump all streams

### ISSUE THREAD

**Issue by otofoto** [christian-intra2net/oledump#1]
How to dump all streams(including orphaned) as is?

**Comment by christian-intra2net** [comment]
I do not quite understand the question. You can dump all streams, including orphaned ones, by running the oledump_all script

**Comment by otofoto** [comment]
No it tries to dump only embedded files but not the stream data.

**Comment by christian-intra2net** [comment]
Oh, I see. The oledump_all.py could be modified to do that, you would just have to invent some file name for the stream and in main(), after `if not dumper.OLE10HeaderPresent(data):` and before `continue` you could do:
```
with open(new_filename, 'rb') as writer:
  writer.write(data)   # the data we already read
  writer.write(stream.read())  # rest of the stream
```

I will not implement this since it is beyond the scope of the script and there are better tools to inspect data in olestreams, e.g .in oletools by decalage2

**Comment by otofoto** [comment]
Oletools doesn't have dump all option. Thanks I was able to dump orphaned streams now only have to recreate the original lost structure.
